"""empty message

Revision ID: f7adf7f224b6
Revises: 
Create Date: 2023-12-13 17:00:35.619347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7adf7f224b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_price', sa.Numeric(
            precision=10,
            scale=2),
            nullable=False,
            server_default='0.00'))
        batch_op.add_column(sa.Column('p_description', sa.Text(), nullable=False))
        batch_op.create_unique_constraint('Product_details', ['p_description'])
        batch_op.drop_column('p_Description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_Description', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('p_description')
        batch_op.drop_column('p_price')

    # ### end Alembic commands ###
